---
- include_vars: ../../vars_main.yml

- name: Instalación de dependencias
  apt:
    name: vsftpd
    update_cache: true
    cache_valid_time: 3600

- name: Modificar archivo de configuracion
  lineinfile:
    path: "{{ archivo_conf }}"
    regexp: "{{ item.FROM }}"
    line: "{{ item.TO }}"
  loop:
    - { FROM: '^#write_enable=YES', TO: 'write_enable=YES' }
    - { FROM: '^#chroot_local_user=YES', TO: 'chroot_local_user=YES' }

- name: Agregar opciones a archivo de configuracion
  blockinfile:
    path: "{{ archivo_conf }}"
    block: |
      user_sub_token={{ usuario }}
      local_root={{ home }}/ftp
      pasv_min_port=30000
      pasv_max_port=31000
      userlist_enable=YES
      userlist_file=/etc/vsftpd.user_list
      userlist_deny=NO
    marker: '# {mark} ANSIBLE MANAGED BLOCK - configuracion FTP'
    insertafter: EOF

- name: Creando archivo con usuarios permitidos
  copy:
    dest: "{{ archivo_usuarios }}"
    content: "{{ usuario }}"
    mode: 0440

- name: Creacion de directorio
  file:
    path: "{{ home }}/ftp"
    state: directory
    mode: '0550'
    owner: "{{ usuario }}"
    group: "{{ grupo }}"

- name: Creacion de directorio para subidas
  file:
    path: "{{ home }}/ftp/upload"
    state: directory
    mode: '0750'
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
  notify: reiniciar
